# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(blank=True, max_length=100)),
                ('line_2', models.CharField(blank=True, max_length=100)),
                ('line_3', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=100)),
                ('area', models.IntegerField(choices=[(0, 'Badenoch and Strathspey'), (1, 'Caithness'), (2, 'Inverness and Nairn'), (3, 'Lochaber'), (4, 'Ross-shire'), (5, 'Skye'), (6, 'Sutherland')], default=0)),
                ('evidence', models.FileField(blank=True, upload_to='client/address_evidence/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('changed_date', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Client'), (1, 'Job Coach'), (2, 'Manager'), (3, 'Partner')], default=0)),
                ('title', models.IntegerField(choices=[(0, 'Mr'), (1, 'Mrs'), (2, 'Miss'), (3, 'Ms')], default=0)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('known_as', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Home'), (1, 'Work'), (2, 'Mobile')], default=2)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Person')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('marital_status', models.IntegerField(choices=[(0, 'Divorced'), (1, 'Married'), (2, 'Separated'), (3, 'Single'), (4, 'TBC'), (5, 'To Be Assigned'), (6, 'Widowed')], default=3)),
                ('ethnicity', models.IntegerField(choices=[(0, 'Asian (Bangladesh)'), (1, 'Asian (Chinese)'), (2, 'Asian (Indian)'), (3, 'Asian (Other)'), (4, 'Asian (Pakistan)'), (5, 'Black (African)'), (6, 'Black (Caribbean)'), (7, 'Black (Other)'), (8, 'Mixed Background'), (9, 'Other Ethinicity'), (10, 'TBC'), (11, 'Traveller/Gypsy'), (12, 'White (English)'), (13, 'White (Irish)'), (14, 'White (Other)'), (13, 'White (Scottish)'), (14, 'White (Welsh)')], default=13)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='client/birth_certs/')),
                ('social_work_involved', models.BooleanField(default=False)),
            ],
            bases=('client.person',),
        ),
        migrations.AddField(
            model_name='telephone',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Telephone', to='client.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='client.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='client.Person'),
        ),
    ]
