# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiocontract',
            name='partner',
        ),
        migrations.AddField(
            model_name='contract',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tio_contract', to=settings.AUTH_USER_MODEL),
        ),
    ]
