# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='education',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=None),
        ),
    ]
