# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='forename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
