# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Canvass'), (1, 'Closed'), (2, 'Education'), (3, 'Employed'), (4, 'Profile'), (5, 'Waiting List'), (6, 'Work Experience')], default=None, null=True),
        ),
    ]
