# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.IntegerField(choices=[(0, 'Divorced'), (1, 'Married'), (2, 'Separated'), (3, 'Single'), (4, 'TBC'), (5, 'To Be Assigned'), (6, 'Widowed')], default=3),
        ),
    ]
