# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'No qualifications'), (1, 'Access 1 or 2'), (2, 'Access 3 or foundation standard grade'), (3, 'General standard grade or intermediate 1'), (4, 'Credit'), (5, 'Standard grade or intermediate 2'), (6, 'Higher'), (7, 'HNC or advanced Higher'), (8, 'HND or Degree')], default=None),
        ),
    ]
