# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170602_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='live_contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='client.Contract'),
        ),
    ]
