# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170516_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
