# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170526_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'AA'), (1, 'ATW'), (2, 'BP (Autism)'), (3, 'Closed'), (4, 'EF'), (5, 'ESF Tracking'), (6, 'ESF/Lottery Tracking'), (7, 'GRFW'), (8, 'HC'), (9, 'Lottery Tracking'), (10, 'MiR'), (11, 'PP'), (12, 'TIO'), (13, 'WFH'), (14, 'WIO'), (15, 'WP')], default=None),
        ),
    ]
