# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170528_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contract_status',
        ),
    ]
