# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_recommended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jsa',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'No'), (1, 'Yes')], default=None),
        ),
    ]
