# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_birth_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='client/birth_certs/'),
        ),
    ]
