# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiocontract',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting info man acceptance'), (1, 'Accepted by info man'), (2, 'Approved by fund man'), (3, 'Rejected by fund man'), (4, 'Acceptance revoked by info man'), (5, 'Awaiting fund manager approval')], default=0),
        ),
    ]
