# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170523_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ethnicity',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Asian (Bangladesh)'), (1, 'Asian (Chinese)'), (2, 'Asian (Indian)'), (3, 'Asian (Other)'), (4, 'Asian (Pakistan)'), (5, 'Black (African)'), (6, 'Black (Caribbean)'), (7, 'Black (Other)'), (8, 'Mixed Background'), (9, 'Other Ethinicity'), (10, 'TBC'), (11, 'Traveller/Gypsy'), (12, 'White (English)'), (13, 'White (Irish)'), (14, 'White (Other)'), (15, 'White (Scottish)'), (16, 'White (Welsh)')], default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Divorced'), (1, 'Married'), (2, 'Separated'), (3, 'Single'), (4, 'TBC'), (5, 'To Be Assigned'), (6, 'Widowed')], default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Male'), (1, 'Female')], default=None),
        ),
    ]
