# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170517_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='changed_date',
            new_name='modfied_date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='changed_by',
            new_name='modified_by',
        ),
    ]
