# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_person_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
