# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_auto_20170526_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Awaiting info man approval'), (1, 'Awaiting fund man approval'), (2, 'Approved by fund man'), (3, 'Rejected by fund man'), (4, 'Accepted by info man')], default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIOContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Contract')),
                ('issue', models.IntegerField(choices=[(None, 'Please select'), (0, 'Learning Difficulty'), (1, 'Autism'), (2, 'Mental Ill Health (3+ yrs, links to CMHT)'), (4, 'Physical and Sensory'), (4, 'Social and Emotional')], default=None, verbose_name='Adult 18+ with')),
                ('consent_form_complete', models.BooleanField(default=False)),
                ('aa_progress_jsa_18', models.BooleanField(default=False, verbose_name='Progressing from Activity Agreements')),
                ('add_support_jsa_18', models.BooleanField(default=False, verbose_name='In need of additional support with health and personal confidence issues')),
                ('add_support_jsa_25', models.BooleanField(default=False, verbose_name='In need of additional support with health and personal confidence issues')),
                ('wca_incapacity', models.BooleanField(default=False, verbose_name='Prior to WCA')),
                ('support_esa', models.BooleanField(default=False, verbose_name='Support Group Category')),
                ('wrag_esa', models.BooleanField(default=False, verbose_name='W.R.A.G (less than 3 months sustained employment in the last 3 yrs)')),
                ('emp_pros_inc', models.BooleanField(default=False, verbose_name='To improve employment prospects')),
                ('other_ben', models.TextField(verbose_name='Other Benefits')),
                ('fund_mgr_notes', models.TextField(verbose_name='Fund Manager Notes')),
            ],
            options={
                'abstract': False,
            },
            bases=('client.contract',),
        ),
    ]
