# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_auto_20170603_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('background_info', models.TextField(verbose_name='Background information')),
                ('pref_job_dir', models.TextField(verbose_name='Preferred job direction (target outcome)')),
                ('prev_work_exp', models.TextField(verbose_name='Previous work experience, including personal feelings on jobs (bullet points)')),
                ('skills', models.TextField(verbose_name='Highlight any skills or qualifications client could bring to a job (bullet points)')),
                ('dev_issues', models.TextField(verbose_name='Highlight any support or development issues (bullet points):')),
                ('other_comments', models.TextField(verbose_name='Other comments/follow up')),
                ('scanned_copy', models.FileField(blank=True, null=True, upload_to='client/init_int/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_created_by', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning', models.TextField(verbose_name='Other relevant learning/experience/skills')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='client.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='OtherAgencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField(choices=[(None, 'Please select'), (0, 'Barnardos'), (1, 'Community Mental Health Team'), (2, 'Department for Work and Pensions'), (3, 'Highland Council Employability'), (4, 'None'), (5, 'Skills Development Scotland'), (6, 'Social Work'), (7, 'Youth Development work')], default=None)),
                ('contact_person', models.TextField()),
                ('contact_details', models.TextField()),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_agencies', to='client.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='OtherProgrammes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.IntegerField(choices=[(None, 'Please select'), (0, 'AA'), (1, 'ATW'), (2, 'BP (Autism)'), (3, 'Closed'), (4, 'EF'), (5, 'ESF Tracking'), (6, 'ESF/Lottery Tracking'), (7, 'GRFW'), (8, 'HC'), (9, 'Lottery Tracking'), (10, 'MiR'), (11, 'PP'), (12, 'TIO'), (13, 'WFH'), (14, 'WIO'), (15, 'WP')], default=None)),
                ('provider', models.TextField()),
                ('end_date', models.CharField(blank=True, max_length=100)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_programmes', to='client.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.TextField(verbose_name='Planned non-certified training (include any actions taken)')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_training', to='client.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='client.Interview')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-start_date', 'created_on')},
        ),
    ]
