# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170517_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='modfied_date',
            new_name='modified_date',
        ),
    ]
