# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_status_tiocontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='client.Contract'),
        ),
    ]
