# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170522_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='recommended_by',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Business Gateway'), (1, 'College'), (2, 'Highland Council Employability team'), (3, 'Jobcentre Plus'), (4, 'Ness Toiletries'), (5, 'NHS'), (6, 'Rag Tag N Textile'), (7, 'Re-registration'), (8, 'School'), (9, 'Shirlie Project'), (10, 'Skills Development Scotland'), (11, 'Social Work'), (12, 'Word of mouth (friend/family)')], default=None),
        ),
    ]
