# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170522_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employment_status',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Economically Inactive'), (1, 'Employed (including self-employed)'), (2, 'Long Term Employed'), (3, 'NEET Inactive'), (4, 'Unemployed')], default=None),
        ),
    ]
