# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_status_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Awaiting info man approval'), (1, 'Awaiting fund man approval'), (2, 'Approved by fund man'), (3, 'Rejected by fund man'), (4, 'Accepted by info man')], default=0)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='client.Contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractstatus_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractstatus_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='status',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='status',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
