# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20170527_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatus',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_status', to='client.Contract'),
        ),
    ]
