# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='STAGE',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Stage 2'), (1, 'Stage 3'), (3, '18+')], default=None, null=True),
        ),
    ]
