# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='client.Note'),
        ),
    ]
