# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20170527_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiocontract',
            name='issue',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Learning Difficulty'), (1, 'Autism'), (2, 'Mental Ill Health (3+ yrs, links to CMHT)'), (4, 'Physical and Sensory'), (4, 'Social and Emotional')], default=None, null=True, verbose_name='Adult 18+ with'),
        ),
    ]
