# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170527_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiocontract',
            name='fund_mgr_notes',
            field=models.TextField(blank=True, verbose_name='Fund Manager Notes'),
        ),
        migrations.AlterField(
            model_name='tiocontract',
            name='other_ben',
            field=models.TextField(blank=True, verbose_name='Other Benefits'),
        ),
    ]
