# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170604_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning',
            field=models.CharField(max_length=300, verbose_name='Other relevant learning/experience/skills'),
        ),
    ]
