# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170522_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_group',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Autism'), (1, 'Dyspraxia'), (2, 'Head Injury'), (3, 'Learning Difficulties'), (4, 'Low Skilled'), (5, 'Mental Health'), (6, 'No Experience of Work'), (7, 'To Be Assigned'), (8, 'Unemployed (Under 3yrs no health issue)'), (9, 'Young People (NEET)')], default=None),
        ),
    ]
