# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ref_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_unemployed',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Up to 6 months'), (1, '6 - 12 months'), (2, '13 - 24 months'), (3, '25 - 36 months'), (4, 'Over 3 years'), (5, 'TBC'), (6, 'Attending School')], default=None),
        ),
    ]
