# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20170604_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheragencies',
            name='contact_details',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='otheragencies',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otherprogrammes',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherprogrammes',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plannedtraining',
            name='training',
            field=models.CharField(max_length=300, verbose_name='Planned non-certified training (include any actions taken)'),
        ),
    ]
