# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20170604_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheragencies',
            name='contact_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='otheragencies',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='otherprogrammes',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
