# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20170604_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheragencies',
            name='agency',
            field=models.IntegerField(choices=[(0, 'Barnardos'), (1, 'Community Mental Health Team'), (2, 'Department for Work and Pensions'), (3, 'Highland Council Employability'), (4, 'None'), (5, 'Skills Development Scotland'), (6, 'Social Work'), (7, 'Youth Development work')], default=0),
        ),
    ]
