# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0012_client_employment_status_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='job_coach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
