# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0013_client_job_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='job_coach',
        ),
        migrations.AddField(
            model_name='client',
            name='job_coach',
            field=models.ManyToManyField(null=True, related_name='job_coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
