# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0014_auto_20170522_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='job_coach',
        ),
        migrations.AddField(
            model_name='client',
            name='job_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
