# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0016_client_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(None, 'Please select'), (0, 'Activity Agreement'), (1, 'Big Picture'), (2, 'Employability Fund'), (3, 'MIR'), (4, 'PP'), (5, 'TIO'), (6, 'Work Programme')], default=None)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('secondary_client_group', models.IntegerField(choices=[(None, 'Please select'), (0, 'Above 54 Years Old'), (1, 'Armed Forces Veteran'), (2, 'Asylum Seeker'), (3, 'Criminal Convictions'), (4, 'Deprived Area'), (5, 'EU Migrant'), (6, 'Homeless Or Threat Of Exclusion'), (7, 'Living In a Jobless Household'), (8, 'Lone Parent'), (9, 'Long Term Unemployed'), (10, 'Low Income Employed'), (11, 'Low Skilled'), (12, 'No Experience Of Work'), (13, 'Primary Carer Of Older Person Over 65'), (14, 'Primary Carer Of Person Under 65'), (15, 'Refugee'), (16, 'Rural Area'), (17, 'Substance Related Issues'), (18, 'To Be Assigned'), (19, 'Underemployed'), (20, 'Young People Leaving Care')], default=None)),
                ('secondary_client_group_evidence', models.FileField(blank=True, null=True, upload_to='client/group_evid/')),
                ('application_form', models.FileField(blank=True, null=True, upload_to='client/con_app_form/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
