# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_otheragencies_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='client',
        ),
        migrations.AddField(
            model_name='interview',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='client.Contract'),
        ),
    ]
