# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20170604_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='interview',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='client.Interview'),
        ),
    ]
