# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='type',
            field=models.IntegerField(choices=[(0, 'Home'), (1, 'Mobile'), (2, 'Parents'), (3, 'Work')], default=1),
        ),
    ]
