# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmltemplate',
            old_name='title',
            new_name='template_identifier',
        ),
    ]
