# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_auto_20170601_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='htmltemplate_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='htmltemplate',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='htmltemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='htmltemplate_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='htmltemplate',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
