# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_auto_20170518_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
