# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170601_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='htmltemplate',
            unique_together=set([('template_identifier', 'type')]),
        ),
    ]
