# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_identifier',
            field=models.IntegerField(choices=[(None, 'Please select'), (0, 'Client main details'), (1, 'Latest client contract'), (2, 'Latest client TIO contract')], default=None, unique=True),
        ),
    ]
