
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from email_template.models import EmailTemplate
from reporting.models import ReportTemplate
from datetime import datetime

User.objects.create_superuser('admin', 'a@a.com', 'new3lifeok')
admin_group = Group(name="admin")
admin_group.save()
client_group = Group(name="client")
client_group.save()
neil = User.objects.create_user(username='neil', email="n.macleod@shirlie.co.uk",  password="neil_1234")
admin_group.user_set.add(neil)
admin_group.save()
job_coach_group = Group(name="job coach")
job_coach_group.save()
job_coach_mgr_group = Group(name="job coach manager")
job_coach_mgr_group.save()
partner_group = Group(name="partner")
partner_group.save()
info_man_group = Group(name="info manager")
info_man_group.save()
supply_chain_man_group = Group(name="supply chain manager")
supply_chain_man_group.save()
rag_tag_group = Group(name="rag tag")
rag_tag_group.save()
hicouncil_group = Group(name="highland council")
hicouncil_group.save()

# run sql to repopulate
ann = User.objects.create_user('ann', 'ann@ann.com', 'ann924nn-*!');ann.is_staff=True;ann.save()
lindasutherland = User.objects.create_user('lindasutherland', 'lindasutherland@shirlie.co.uk', 'lindasutherland924in-*!');lindasutherland.is_staff=True;lindasutherland.save()
jobcoach = User.objects.create_user('jobcoach', 'jobcoach@gmail.com', 'jobcoach924ob-*!');jobcoach.is_staff=True;jobcoach.save()
traceythomson = User.objects.create_user('traceythomson', 'traceythomson@shirlie.co.uk', 'traceythomson924ra-*!');traceythomson.is_staff=True;traceythomson.save()
mattest = User.objects.create_user('mattest', 'mattest@a.com', 'mattest924at-*!');mattest.is_staff=True;mattest.save()
alanryndycz = User.objects.create_user('alanryndycz', 'alanryndycz@shirlie.co.uk', 'alanryndycz924la-*!');alanryndycz.is_staff=True;alanryndycz.save()
donnielamont = User.objects.create_user('donnielamont', 'donnielamont@shirlie.co.uk', 'donnielamont924on-*!');donnielamont.is_staff=True;donnielamont.save()
ellenreid = User.objects.create_user('ellenreid', 'ellenreid@shirlie.co.uk', 'ellenreid924ll-*!');ellenreid.is_staff=True;ellenreid.save()
emmamackinnon = User.objects.create_user('emmamackinnon', 'emmamacKinnon@shirlie.co.uk', 'emmamackinnon924mm-*!');emmamackinnon.is_staff=True;emmamackinnon.save()
harrygillespie = User.objects.create_user('harrygillespie', 'harrygillespie@shirlie.co.uk', 'harrygillespie924ar-*!');harrygillespie.is_staff=True;harrygillespie.save()
jrynabatters = User.objects.create_user('jrynabatters', 'jrynabatters@shirlie.co.uk', 'jrynabatters924ry-*!');jrynabatters.is_staff=True;jrynabatters.save()
laurenblack = User.objects.create_user('laurenblack', 'laurenblack@shirlie.co.uk', 'laurenblack924au-*!');laurenblack.is_staff=True;laurenblack.save()
lynneread = User.objects.create_user('lynneread', 'lynneread@shirlie.co.uk', 'lynneread924yn-*!');lynneread.is_staff=True;lynneread.save()
marionscott = User.objects.create_user('marionscott', 'marionscott@shirlie.co.uk', 'marionscott924ar-*!');marionscott.is_staff=True;marionscott.save()
marksmyth = User.objects.create_user('marksmyth', 'marksmyth@shirlie.co.uk', 'marksmyth924ar-*!');marksmyth.is_staff=True;marksmyth.save()
moragabernethy = User.objects.create_user('moragabernethy', 'moragabernethy@shirlie.co.uk', 'moragabernethy924or-*!');moragabernethy.is_staff=True;moragabernethy.save()
neillianrodger = User.objects.create_user('neillianrodger', 'neillianrodger@shirlie.co.uk', 'neillianrodger924ei-*!');neillianrodger.is_staff=True;neillianrodger.save()
robford = User.objects.create_user('robford', 'robford@shirlie.co.uk', 'robford924ob-*!');robford.is_staff=True;robford.save()
sharoncameron = User.objects.create_user('sharoncameron', 'sharoncameron@shirlie.co.uk', 'sharoncameron924ha-*!');sharoncameron.is_staff=True;sharoncameron.save()
shonaellis = User.objects.create_user('shonaellis', 'shonaellis@shirlie.co.uk', 'shonaellis924ho-*!');shonaellis.is_staff=True;shonaellis.save()
simonetot = User.objects.create_user('simonetot', 'simoneduncan@shirlie.co.uk', 'simonetot924im-*!');simonetot.is_staff=True;simonetot.save()
annlee = User.objects.create_user('annlee', 'annlee@shirlie.co.uk', 'annlee924nn-*!');annlee.is_staff=True;annlee.save()
maryfleming = User.objects.create_user('maryfleming', 'maryfleming@shirlie.co.uk', 'maryfleming924ar-*!');maryfleming.is_staff=True;maryfleming.save()
christinebruce = User.objects.create_user('christinebruce', 'christinebruce@shirlie.co.uk', 'christinebruce924hr-*!');christinebruce.is_staff=True;christinebruce.save()
lizgibson = User.objects.create_user('lizgibson', 'reception2@shirlie.co.uk', 'lizgibson924iz-*!');lizgibson.is_staff=True;lizgibson.save()
reception = User.objects.create_user('reception', 'reception@shirlie.co.uk', 'reception924ec-*!');reception.is_staff=True;reception.save()
stephwood = User.objects.create_user('stephwood', 'stephaniewood@shirlie.co.uk', 'stephwood924te-*!');stephwood.is_staff=True;stephwood.save()
infoman = User.objects.create_user('infoman', 'stevemcgonigal@yahoo.co.uk', 'infoman924nf-*!');infoman.is_staff=True;infoman.save()
janemacdonald = User.objects.create_user('janemacdonald', 'janemacDonald@shirlie.co.uk', 'janemacdonald924an-*!');janemacdonald.is_staff=True;janemacdonald.save()
stephengibson = User.objects.create_user('stephengibson', 'stephengibson@shirlie.co.uk', 'stephengibson924te-*!');stephengibson.is_staff=True;stephengibson.save()
svqassessor = User.objects.create_user('svqassessor', 'svqassessor@svq.com', 'svqassessor924vq-*!');svqassessor.is_staff=True;svqassessor.save()
jobcoach2 = User.objects.create_user('jobcoach2', 'mcgonigalstephen@gmail.com', 'jobcoach2924ob-*!');jobcoach2.is_staff=True;jobcoach2.save()
fionahawthorne = User.objects.create_user('fionahawthorne', 'fionahawthorne@shirlie.co.uk', 'fionahawthorne924io-*!');fionahawthorne.is_staff=True;fionahawthorne.save()
angusmaclennan = User.objects.create_user('angusmaclennan', 'angusmaclennan@shirlie.co.uk', 'angusmaclennan924ng-*!');angusmaclennan.is_staff=True;angusmaclennan.save()
minettemaclennan = User.objects.create_user('minettemaclennan', 'minettemaclennan@shirlie.co.uk', 'minettemaclennan924in-*!');minettemaclennan.is_staff=True;minettemaclennan.save()
jamesmacdonald = User.objects.create_user('jamesmacdonald', 'jamesmacdonald@shirlie.co.uk', 'jamesmacdonald924am-*!');jamesmacdonald.is_staff=True;jamesmacdonald.save()
markmackenzie = User.objects.create_user('markmackenzie', 'markmackenzie@shirlie.co.uk', 'markmackenzie924ar-*!');markmackenzie.is_staff=True;markmackenzie.save()
lucybeattie = User.objects.create_user('lucybeattie', 'lucybeattie@shirlie.co.uk', 'lucybeattie924uc-*!');lucybeattie.is_staff=True;lucybeattie.save()
paulsloan = User.objects.create_user('paulsloan', 'paulsloan@shirlie.co.uk', 'paulsloan924au-*!');paulsloan.is_staff=True;paulsloan.save()
jemmatweedie = User.objects.create_user('jemmatweedie', 'jemmatweedie@shirlie.co.uk', 'jemmatweedie924em-*!');jemmatweedie.is_staff=True;jemmatweedie.save()
ashleymurray = User.objects.create_user('ashleymurray', 'ashleymurray@shirlie.co.uk', 'ashleymurray924sh-*!');ashleymurray.is_staff=True;ashleymurray.save()
kirsty = User.objects.create_user('kirsty', 'kirstygillies@shirlie.co.uk', 'kirsty924ir-*!');kirsty.is_staff=True;kirsty.save()
hayleysangster = User.objects.create_user('hayleysangster', 'hayleysangster@shirlie.co.uk', 'hayleysangster924ay-*!');hayleysangster.is_staff=True;hayleysangster.save()
judy = User.objects.create_user('judy', 'judyspark@shirlie.co.uk', 'judy924ud-*!');judy.is_staff=True;judy.save()
meghanmackenzie = User.objects.create_user('meghanmackenzie', 'meghanmackenzie@shirlie.co.uk', 'meghanmackenzie924eg-*!');meghanmackenzie.is_staff=True;meghanmackenzie.save()
jillian = User.objects.create_user('jillian', 'jillianbaird@shirlie.co.uk', 'jillian924il-*!');jillian.is_staff=True;jillian.save()
markdowney = User.objects.create_user('markdowney', 'm.downey@shirliie.co.uk', 'markdowney924ar-*!');markdowney.is_staff=True;markdowney.save()
darrenhamilton = User.objects.create_user('darrenhamilton', 'd.hamilton@shirlie.co.uk', 'darrenhamilton924ar-*!');darrenhamilton.is_staff=True;darrenhamilton.save()
heatherharper = User.objects.create_user('heatherharper', 'h.harper@shirlie.co.uk', 'heatherharper924ea-*!');heatherharper.is_staff=True;heatherharper.save()
scottfraser = User.objects.create_user('scottfraser', 's.fraser@shirlie.co.uk', 'scottfraser924co-*!');scottfraser.is_staff=True;scottfraser.save()
dawncattanach = User.objects.create_user('dawncattanach', 'd.cattanach@shirlie.co.uk', 'dawncattanach924aw-*!');dawncattanach.is_staff=True;dawncattanach.save()
closed = User.objects.create_user('closed', 'closed@closed', 'closed123');
neilmacleod = User.objects.create_user('neilmacleod', 'neilmacLeod@shirlie.co.uk', 'neilmacleod924ei-*!');neilmacleod.is_staff=True;neilmacleod.save()
hicouncil = User.objects.create_user('hicouncil', 'highlandcouncil123@gmail.com', 'hicouncil924ic-*!');hicouncil.is_staff=True;hicouncil.save()
ragtag = User.objects.create_user('ragtag', 'ragtag1456@gmail.com', 'ragtag924ag-*!');ragtag.is_staff=True;ragtag.save()
janegair = User.objects.create_user('janegair', 'Jane.gair@highland-opportunity.com', 'janegair924an-*!');janegair.is_staff=True;janegair.save()
vickysamuels = User.objects.create_user('vickysamuels', 'vickisamuels@yahoo.co.uk', 'vickysamuels924ic-*!');vickysamuels.is_staff=True;vickysamuels.save()
joan = User.objects.create_user('joan', 'joan.mackay@ragtagskye.org', 'joan924oa-*!');joan.is_staff=True;joan.save()
hicounciluser = User.objects.create_user('hicounciluser', 'hicouncil@hicouncil.com', 'hicounciluser924ic-*!');hicounciluser.is_staff=True;hicounciluser.save()
# run sql to repopulate
job_coach_group.user_set.add(ann)
job_coach_group.user_set.add(lindasutherland)
job_coach_group.user_set.add(jobcoach)
job_coach_group.user_set.add(traceythomson)
job_coach_group.user_set.add(mattest)
job_coach_group.user_set.add(alanryndycz)
job_coach_group.user_set.add(donnielamont)
job_coach_group.user_set.add(ellenreid)
job_coach_group.user_set.add(emmamackinnon)
job_coach_group.user_set.add(harrygillespie)
job_coach_group.user_set.add(jrynabatters)
job_coach_group.user_set.add(laurenblack)
job_coach_group.user_set.add(lynneread)
job_coach_group.user_set.add(marionscott)
job_coach_group.user_set.add(marksmyth)
job_coach_group.user_set.add(moragabernethy)
job_coach_group.user_set.add(neillianrodger)
job_coach_group.user_set.add(robford)
job_coach_group.user_set.add(sharoncameron)
job_coach_group.user_set.add(shonaellis)
job_coach_group.user_set.add(simonetot)
job_coach_group.user_set.add(annlee)
job_coach_group.user_set.add(maryfleming)
job_coach_group.user_set.add(christinebruce)
job_coach_group.user_set.add(lizgibson)
job_coach_group.user_set.add(reception)
job_coach_group.user_set.add(stephwood)
job_coach_group.user_set.add(infoman)
job_coach_group.user_set.add(janemacdonald)
job_coach_group.user_set.add(stephengibson)
job_coach_group.user_set.add(svqassessor)
job_coach_group.user_set.add(jobcoach2)
job_coach_group.user_set.add(fionahawthorne)
job_coach_group.user_set.add(angusmaclennan)
job_coach_group.user_set.add(minettemaclennan)
job_coach_group.user_set.add(jamesmacdonald)
job_coach_group.user_set.add(markmackenzie)
job_coach_group.user_set.add(lucybeattie)
job_coach_group.user_set.add(paulsloan)
job_coach_group.user_set.add(jemmatweedie)
job_coach_group.user_set.add(ashleymurray)
job_coach_group.user_set.add(kirsty)
job_coach_group.user_set.add(hayleysangster)
job_coach_group.user_set.add(judy)
job_coach_group.user_set.add(meghanmackenzie)
job_coach_group.user_set.add(jillian)
job_coach_group.user_set.add(markdowney)
job_coach_group.user_set.add(darrenhamilton)
job_coach_group.user_set.add(heatherharper)
job_coach_group.user_set.add(scottfraser)
job_coach_group.user_set.add(dawncattanach)
job_coach_group.user_set.add(closed)
partner_group.user_set.add(stephengibson)
partner_group.user_set.add(stephwood)
partner_group.user_set.add(ragtag)
partner_group.user_set.add(infoman)
partner_group.user_set.add(christinebruce)
partner_group.user_set.add(joan)
partner_group.user_set.add(vickysamuels)
partner_group.user_set.add(annlee)
partner_group.user_set.add(traceythomson)
job_coach_mgr_group.user_set.add(mattest)
job_coach_mgr_group.user_set.add(reception)
job_coach_mgr_group.user_set.add(jobcoach)
job_coach_mgr_group.user_set.add(stephwood)
job_coach_mgr_group.user_set.add(christinebruce)
job_coach_mgr_group.user_set.add(traceythomson)
job_coach_mgr_group.user_set.add(fionahawthorne)
job_coach_mgr_group.user_set.add(annlee)
job_coach_mgr_group.user_set.add(meghanmackenzie)
job_coach_mgr_group.user_set.add(jillian)
info_man_group.user_set.add(ann)
info_man_group.user_set.add(traceythomson)
info_man_group.user_set.add(lizgibson)
info_man_group.user_set.add(infoman)
info_man_group.user_set.add(stephwood)
info_man_group.user_set.add(christinebruce)
info_man_group.user_set.add(maryfleming)
info_man_group.user_set.add(fionahawthorne)
info_man_group.user_set.add(stephengibson)
info_man_group.user_set.add(annlee)
info_man_group.user_set.add(meghanmackenzie)
info_man_group.user_set.add(jillian)
supply_chain_man_group.user_set.add(stephengibson)
supply_chain_man_group.user_set.add(stephwood)
supply_chain_man_group.user_set.add(infoman)
supply_chain_man_group.user_set.add(christinebruce)
supply_chain_man_group.user_set.add(traceythomson)
supply_chain_man_group.user_set.add(annlee)
hicouncil_group.user_set.add(hicouncil)
hicouncil_group.user_set.add(janegair)
hicouncil_group.user_set.add(hicounciluser)
hicouncil_group.user_set.add(neilmacleod)
rag_tag_group.user_set.add(ragtag)
rag_tag_group.user_set.add(joan)
rag_tag_group.user_set.add(vickysamuels)

job_coach_group.save()
partner_group.save()
job_coach_mgr_group.save()
info_man_group.save()
supply_chain_man_group.save()
hicouncil_group.save()
rag_tag_group.save()
