# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='bcc_address',
            new_name='bcc_addresses',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='cc_address',
            new_name='cc_addresses',
        ),
    ]
