# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0002_auto_20170601_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='to_address',
            field=models.TextField(),
        ),
    ]
